# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "pipeline-with-infracost-state-backend"
    dynamodb_table = "pipeline-with-infracost-state-backend"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-central-1"
  }
}
